# Generated by Django 5.0 on 2024-01-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='angle',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desk',
            name='height',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desk',
            name='width',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desk',
            name='x_position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desk',
            name='y_position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
